version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/CyberdyneHQ/<repository-name>"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "prettier"

[[transformers]]
name = "black"